site_name: my memos
theme: 
  name: 'material'
markdown_extensions:
  - codehilite
pages:
- Home: index.md
- MkDocs: mkdocs/useguide.md
- Chrome:
  - 实用技巧: chrome/tricks.md
- Git:
  - 开启ss代理加速: git/proxy.md