site_name: my memos
theme: 
  name: 'material'
markdown_extensions:
  - codehilite
pages:
- Home: index.md
- MkDocs: mkdocs/useguide.md
- Python:
  - 魔术方法: python/magic.md
- Chrome:
  - 实用技巧: chrome/tricks.md
- Git:
  - 常见命令: git/commands.md
  - 开启ss代理加速: git/proxy.md
- C++:
  - 学习路线: C++/index.md
- ftp:
  - 安装与使用: ftp/index.md
- ss:
  - ubuntu上使用shaodwsocks-qt5: ss/ubuntu_ss.md
- misc:
  - Windows命令行代理: misc/cmd_proxy.md
